CREATE SCHEMA MUPRR;
GO
CREATE TABLE MUPRR.logs(
	id int identity not null primary key,
	context varchar(255) not null,
	description varchar(255),
	date datetime not null DEFAULT GETDATE(),
)
CREATE TABLE MUPRR.BRB_RCU_ASSOC(
	RCU_ID VARCHAR(255) NOT NULL PRIMARY KEY,
	BRB_ID VARCHAR(255) NOT NULL,
	UU VARCHAR(255)
);
CREATE TABLE MUPRR.Vinculo (
    id int NOT NULL IDENTITY,
    sigla varchar(255) NOT NULL,
    descricao varchar(255),
    PRIMARY KEY (id)
);
CREATE TABLE MUPRR.UnidadeOrganica(
    id int NOT NULL IDENTITY,
    sigla varchar(255) NOT NULL,
    descricao varchar(255),
    PRIMARY KEY (id)
);
CREATE TABLE MUPRR.ClassroomGroup(
	id VARCHAR(255) NOT NULL PRIMARY KEY,
	name VARCHAR(255)
);
CREATE TABLE MUPRR.Profile(
	id VARCHAR(255) NOT NULL PRIMARY KEY,
	name VARCHAR(255),
	priority int 
);
ALTER TABLE MUPRR.Profile ADD CONSTRAINT priority_unique UNIQUE (priority)
CREATE TABLE MUPRR.MUP(
    id INT NOT NULL IDENTITY,
    uo INT NOT NULL,
	vinculo INT NOT NULL,
    profile varchar(255) NOT NULL,
	classGroup VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),

	FOREIGN KEY (uo) REFERENCES MUPRR.Vinculo(id),
	FOREIGN KEY (vinculo) REFERENCES MUPRR.UnidadeOrganica(id),
	FOREIGN KEY (profile) REFERENCES MUPRR.ClassroomGroup(id),
	FOREIGN KEY (classGroup) REFERENCES MUPRR.Profile(id),
);
CREATE TABLE MUPRR.logs(
	id int identity not null primary key,
	context varchar(255) not null,
	date datetime not null DEFAULT GETDATE(),
)


INSERT INTO MUPRR.UnidadeOrganica VALUES
    ('AAC',' Área de Apoio ao Cliente'),
    ('AAITI',' Área de Apoio à Inovação, Transferência de Tecnologia e Internacionalização'),
    ('AAMU',' Área Arquivo e Museu'),
    ('ABIB',' Área de Bibilioteca'),
    ('ACAL',' Área de Contratos e Apoio Logístico'),
    ('ACP',' Área de Contabilidade e Património'),
    ('AISCS',' Área de Infraestruturas de Serviços, Comunicações e Segurança'),
    ('AJ',' Assessoria Jurídica'),
    ('AMIP',' Área de Mobilidade e Integração Profissional'),
    ('AOIE',' Área de Obras, Infraestrutura e Equipamentos'),
    ('ARA',' Área de Registos Académicos'),
    ('AREAU',' Área de Recursos Electrónicos e Apoio ao Utilizador'),
    ('ARF',' Área de Recursos Financeiros'),
    ('ARH',' Área de Recursos Humanos'),
    ('ARUA',' Associação de Radioamadorismo da UA'),
    ('ASDT',' Área de Segurança e Desenvolvimento Técnico'),
    ('ASGI',' Área de Sistemas de Gestão de Informação'),
    ('AVEIRODOMUS',' Aveiro Domus'),
    ('CBC',' Centro de Biologia Celular'),
    ('CCICFACI',' Com. Cient. Independente para o controlo e Fiscal. Ambiental da Co-Inc'),
    ('CCPSF',' Construção do Conhecimento Pedagógico nos Sistemas de Formação'),
    ('CDTFF',' Centro de Investigação em Didática e Tecnologia na Formação de Formado'),
    ('CECE',' Centro de Estudos de Competividade Empresarial'),
    ('CEFASI',' Centro de Especialização e Formação Avançada para os Serviços e Indústria'),
    ('CEGOPP',' Centro de Estudos em Governança e Políticas Públicas'),
    ('CEJ',' Centro de Estudos Jazz'),
    ('CEOC',' Centro de Estudos em Optimização e Controlo'),
    ('CIDTFF',' Centro de Investigação em Didáctica e Tecnologia na Formação de Formado'),
    ('CIECC',' Centro de Investigação em Educação e Ciências do Comportamento'),
    ('CLLC',' Centro de Línguas, Literaturas e Culturas'),
    ('CUCF',' Centro Universitário de Fé e Cultura'),
    ('ELMAS',' Evolução Litosférica e Meio Ambiental de Superfície'),
    ('FJJMCE',' Comissão Editorial'),
    ('FS',' Formação e Serviço'),
    ('FSCOSD',' Física de Semicondutores em Camadas, Optoelectrónica e Sistemas Desord'),
    ('GAPI',' Gabinete de Apoio à Promoção da Propriedade Industrial'),
    ('GAQAP',' Gabinete de Qualidade, Avaliação e Procedimentos'),
    ('GBU',' Grupo Bíblico UniversitárioGEOBIOTEC Geobiociências, Geotecnologias e Geo-engenharias'),
    ('GOVCOPP',' Unidade de Investigação em Governança, Competitividade e Políticas Públicas'),
    ('GUD',' Gabinete Universidade Digital'),
    ('GUE',' Gabinete Universidade/Empresa'),
    ('IFIU',' Instituto de Formação Inicial Universitária'),
    ('IFPG',' Instituto de Formação Pós-Graduada'),
    ('IFSP',' Instituto de Formação Superior Politécnica'),
    ('IHCT',' Instituto de História da Ciência e da Técnica'),
    ('INET-MD',' Pólo de Aveiro do I. de Etnomusicologia - Centro de Estudos de Música e D'),
    ('IRL',' Instituto Rodrigues Lapa'),
    ('MA',' Matemática e Aplicações'),
    ('MIA',' Minerais Industriais e Argilas'),
    ('QOPNA',' Química Orgânica de Produtos Naturais e Agroalimentares'),
    ('SUA',' Senado'),
    ('TEMA',' Centro de Tecnologia Mecânica e Automação'),
    ('UATEC',' Unidade de Transferência de Tecnologia'),
    ('UNICA',' Unidade de Investigação em Comunicação e Arte'),
    ('AAAUA',' Associação dos Antigos Alunos da UA'),
    ('AAUAV',' Associação Académica da Universidade de Aveiro'),
    ('ADM',' Administração'),
    ('AEISCA',' Associação de Estudantes do ISCAA'),
    ('AFUAV',' Associação de Funcionários da Universidade de Aveiro'),
    ('AVEIRO-DIGITAL',' Aveiro Digital'),
    ('BIO',' Departamento de Biologia'),
    ('CC',' Conselho Científico'),
    ('CEMED',' Centro Multimédia e de Ensino à Distância'),
    ('CESAM',' Centro de Estudos do Ambiente e do Mar'),
    ('CETACMEDIA',' Pólo de Aveiro do Centro de Estudos das Tecnologias e Ciências da Comunicação'),
    ('CG',' Conselho Geral'),
    ('CGEST',' Conselho de Gestão'),
    ('CIAQ',' Centro de Infância Arte e Qualidade'),
    ('CICECO',' Centro de Investigação em Materiais Cerâmicos e Compósitos'),
    ('CICUA',' Centro de Informática e Comunicações'),
    ('CIFOP',' Centro Integrado de Formação de Professores'),
    ('CP',' Conselho Pedagógico'),
    ('CPCT',' Complexo Pedagógico, Científico e Tecnológico'),
    ('CS',' Secção Autónoma de Ciências da Saúde'),
    ('DAO',' Departamento de Ambiente e Ordenamento'),
    ('DCE',' Departamento de Ciências da Educação'),
    ('DCSPT',' Departamento Ciências Sociais, Políticas e do Território'),
    ('DE',' Departamento de EducaçãoDECA Departamento de Comunicação e Arte'),
    ('DECIVIL',' Departamento de Engenharia Civil'),
    ('DEGEI',' Departamento de Economia, Gestão e Engenharia Industrial'),
    ('DEM',' Departamento de Engenharia Mecânica'),
    ('DEMAC',' Departamento de Engenharia de Materiais e Cerâmica'),
    ('DETI',' Departamento de Electrónica, Telecomunicações e Informática'),
    ('DLC',' Departamento de Línguas e Culturas'),
    ('DMAT',' Departamento de Matemática'),
    ('DQ',' Departamento de Química'),
    ('DRH',' Área de Recursos Humanos'),
    ('DSA',' Divisão de Serviços Académicos'),
    ('DSN',' Departamento sem nome'),
    ('DTE',' Departamento de Didáctica e Tecnologia Educativa'),
    ('EDUA',' Escola Doutoral da Universidade de Aveiro'),
    ('ESAN',' Escola Superior de Design, Gestão e Tecnologia da Produção'),
    ('ESSUA',' Escola Superior de Saúde'),
    ('ESTGA',' Escola Superior de Tecnologia e Gestão de Águeda'),
    ('FCCV',' Fábrica - Ciência Viva'),
    ('FIS',' Departamento de Física'),
    ('FJJM',' Fundação João Jacinto de Magalhães'),
    ('GAGI',' Gabinete de Gestão da Informação'),
    ('GEO',' Departamento de Geociências'),
    ('GOVUA',' Orgãos de Governo da Universidade de Aveiro'),
    ('GRUPUNAVE',' GrupUNAVE'),
    ('I3N',' Inst.Nanoestruturas, Nanomodelação, NanoFabricação-Física de Semicondutores'),
    ('IC-UA',' Instituto Confúcio da Universidade de Aveiro'),
    ('IDAD',' Instituto do Ambiente e Desenvolvimento'),
    ('IEETA',' Instituto de Engenharia Electrónica e Telemática de Aveiro'),
    ('IEUA',' Incubadora de Empresas da Universidade de Aveiro'),
    ('II',' Núcleo do Bolseiro'),
    ('ISCA',' Instituto Superior de Contabilidade e Administração de Aveiro'),
    ('IT',' Instituto de Telecomunicações'),
    ('JAZZPORTUGAL.UA.PT',' Jazz Portugal'),
    ('LCA',' Laboratório Central de Análises'),
    ('PAN',' Programa Aveiro-Norte'),
    ('PCMU',' Programa Carnegie Mellon University'),
    ('PMATE',' PMATE - Projecto Matemática Ensino'),
    ('REIT-GERAL',' Reitoria Geral'),
    ('RT',' Reitoria'),
    ('SAA',' Serviços Académicos e Administrativos'),
    ('SAAR',' Secretariado de Apoio aos Antigos ReitoresSAC Área de Contratos e Apoio Logístico'),
    ('SAS',' Serviços de Acção Social'),
    ('SBIDM',' Serviço de Bibliotecas, Informação Documental e Museologia'),
    ('SCIRP',' Serviços de Comunicação, Imagem e Relações Públicas'),
    ('SDUA',' Serviços de Documentação'),
    ('SFP',' Serviços Financeiros e Património'),
    ('SGA',' Serviço de Gestão Académica'),
    ('SGRF',' Serviços de Gestão de Recursos Financeiros'),
    ('SGRH',' Serviços de Gestão de Recursos Humanos'),
    ('SGRHF',' Serviço de Gestão De Recursos Humanos e Financeiros'),
    ('SGTL',' Serviço de Gestão Técnica e Logística'),
    ('SICRE',' Serviço de Inovação, Cooperação e Relações com o Exterior'),
    ('SPR.UA.PT',' Sociedade Portuguesa de Robótica'),
    ('SRE',' Serviços de Relações Externas'),
    ('STEC',' Serviços Técnicos'),
    ('STIC',' Serviço de Tecnologias de Informação e Comunicação'),
    ('STICM',' Serviço de Tecnologias de Informação e Comunicação (MGMT)'),
    ('UA',' Universidade de Aveiro'),
    ('UINFOC',' Unidade Integrada de Formação Continuada'),
    ('UNAVE',' Associação para a Formação Profissional e Investigação da UA');






